server:
  port: 8082

spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:mysql://localhost:3306/doctor_db?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true